#!/usr/bin/env python3
"""Turn compiled kernel images into a C header the library can compile in.

A .spex is a raw block of instruction words. The library needs those words in memory at
run time, and shipping them as data files would mean an installed library had to find its
own data directory first. Embedding them removes that problem entirely, at the cost of this
generator.

The words are emitted little-endian, which is what `riscv64-unknown-elf-objcopy -O binary`
writes and what the device reads.
"""

import argparse
import pathlib
import struct
import sys

WORDS_PER_LINE = 4


def kernel_name(path: pathlib.Path) -> str:
    """`kernel_bind.spex` -> `bind`."""
    stem = path.stem
    return stem[len("kernel_"):] if stem.startswith("kernel_") else stem


def read_words(path: pathlib.Path) -> list[int]:
    payload = path.read_bytes()
    if not payload:
        raise SystemExit(f"{path}: the image is empty, so the kernel would do nothing.")
    if len(payload) % 4 != 0:
        raise SystemExit(f"{path}: {len(payload)} bytes is not a whole number of instruction words.")
    return [word for (word,) in struct.iter_unpack("<I", payload)]


def emit(out, images: dict[str, list[int]]) -> None:
    out.write("/* Generated by scripts/embed_kernels.py. Do not edit; edit the kernels instead. */\n")
    out.write("\n#ifndef SPARSR_HDC_KERNEL_IMAGES_H\n#define SPARSR_HDC_KERNEL_IMAGES_H\n\n")
    out.write("#include <stdint.h>\n\n")

    for name, words in images.items():
        out.write(f"static const uint32_t hdc_kernel_{name}_image[] = {{\n")
        for start in range(0, len(words), WORDS_PER_LINE):
            line = ", ".join(f"0x{word:08x}u" for word in words[start:start + WORDS_PER_LINE])
            out.write(f"    {line},\n")
        out.write("};\n\n")

    out.write("#endif /* SPARSR_HDC_KERNEL_IMAGES_H */\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("images", nargs="+", type=pathlib.Path)
    arguments = parser.parse_args()

    images = {kernel_name(path): read_words(path) for path in arguments.images}

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    with arguments.output.open("w", encoding="utf-8") as out:
        emit(out, images)

    total = sum(len(words) for words in images.values())
    print(f"embed_kernels: {len(images)} kernels, {total} instruction words -> {arguments.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
